import { ReactNode } from 'react';
import { ReduxProvider } from '@app/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ReduxProvider>
      <html lang='en'>
        <body style={{ display: 'none' }}>{children}</body>
      </html>
    </ReduxProvider>
  );
}
