import '@styles/globals.css';
import { ReduxProviders } from '@components/global/redux/Redux.provider';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { Background } from '@components/global/Background';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ReduxProviders>
          <UserProvider>
            <Background>{children}</Background>
          </UserProvider>
        </ReduxProviders>
      </body>
    </html>
  );
}
